version: '3.7'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pg_password
      POSTGRES_DB: pg_database
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432

networks:
  postgres:


volumes:
  postgres:
